### ISSUE TITLE
Issues with pytransform for running Artisan on Linux

### ISSUE THREAD

**Issue by CatalinAlexandruPX** [Bleemsys/Artisan-Core#2]
Hi, the package is looking very interesting, and I would like to try it!

I am attempting to run Artisan on (rocky) Linux, within a conda environment python 3.9, however, from what I see you only support Windows based on the pyarmor. This is due to the following error:

```
python ArtisanMain.py -f .//Test_json//EngineBracket_HS_Infill_Lin_LR.json
Could not find "/home/username/Artisan-Core/pytransform/platforms/linux/x86_64/_pytransform.so"
```

Does this only work on Windows? I would assume it can work on Linux systems as well. 
If possible, could you by any chance include the `_pytransform.so` with your package after it run through pyarmor? Thank you!

**Comment by Bleemsys** [comment]
Sorry about later response. The current package only runs on Windows platform. It is likely to compile the C++ base code on Linux platform. Will find a chance to do so. Thanks.
